### ISSUE TITLE
Py2exe is missing from PyPI, making it seem like installation has failed

### ISSUE THREAD

**Issue by enolan** [tweecode/twine#108]
This is what happens:

enolan at enolan-desktop in ~/junk/klklklkl/twine [master] 
$ pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): py2app==0.6.4 in /home/enolan/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Downloading/unpacking py2exe==0.6.9 (from -r requirements.txt (line 2))
  Could not find any downloads that satisfy the requirement py2exe==0.6.9 (from -r requirements.txt (line 2))
Cleaning up...
No distributions at all found for py2exe==0.6.9 (from -r requirements.txt (line 2))
Storing complete log in /home/enolan/.pip/pip.log

I ended up thinking something was wrong and wasted half an hour. Save the next person?

**Comment by cdr255** [comment]
+1 for this being clarified in the README. The language in that section leads one to believe that the following steps will work on *nix, and that line spits out an error that leads the user to believe something is wrong.
