### ISSUE TITLE
Strange characters produced by emacs keybindings

### ISSUE THREAD

**Issue by hypotext** [tweecode/twine#141]
This happens in Twine 1.4.1 on OS X 10.7.4:

![screenshot 2014-04-18 13 01 28](https://cloud.githubusercontent.com/assets/2762356/2743829/30ff5c24-c71b-11e3-9ed3-ac94ebdb1381.png)

Not sure what the symbols are, and the cursor doesn't move either (e.g. C-e doesn't move to the end of the line). Is there some way I could use emacs keybindings in Twine?

**Comment by webbedspace** [comment]
This will probably never get off the ground, regrettably.

**Comment by gdbing** [comment]
I added support for the OSX system default emacs hotkeys to my fork. It's super hacky and shouldn't be merged back, but if anyone else is looking for a whatever-works style solution, they can find it at https://github.com/gdbing/twine
