### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by martinellison** [tweecode/twine#168]
I get endless messages:

TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/martin/Downloads/twine/twine-master/storypanel.py", line 580, in followDrag
    for widget in self.draggingWidgets:

This happens when I start Twine for the first time.

Source is a download of the zip file from GitHub (running on Fedora).

**Comment by webbedspace** [comment]
Try it again now, please.

**Comment by webbedspace** [comment]
Closing due to an inability to reproduce and a lack of response (sorry).
