### ISSUE TITLE
Twine 1.4.2 listed as 1.4.1 in Windows Add or Remove Programs screen

### ISSUE THREAD

**Issue by greyelf** [tweecode/twine#169]
The Twine 1.4.2 installer incorrectly lists the product as Twine 1.4.1 within Windows "Add or Remove Programs" screen on WinXP and also within the related screen on Win7

**Comment by webbedspace** [comment]
This bug was in 1.4.2's [install.nsi](https://github.com/tweecode/twine/blob/9c2081864494f651494fe08e595937ce968de4b6/install.nsi) but has been fixed in the current head.
