### ISSUE TITLE
Is there an option to create custom exporters?

### ISSUE THREAD

**Issue by JulianBissekkou** [tweecode/twine#196]
It would be nice to export stories in different file formats for example as json.
The Documentation contains no information about this. How can this be done?

**Comment by mcdemarco** [comment]
It's a general Twine restriction that output is in HTML only, though there are workarounds used by some story formats to output other file types.  See the [story format catalog](http://mcdemarco.net/tools/hyperfic/twine/catalog/#Proofing.and.other.utility.formats) for some examples.  

Also, this repository is from a previous version of Twine.  See the [current twinejs project](https://github.com/klembot/twinejs/) for the latest in Twine development.
