### ISSUE TITLE
search functionality needed in passage editor

### ISSUE THREAD

**Issue by m8ram** [tweecode/twine#197]
The search function on the main story screen is able to highlight passages that contain a certain string.
But when opening the passage there is currently (twine 2.3.9) no way to navigate to the specific string.

When editing large passages a search function would be very useful.

**Comment by mcdemarco** [comment]
This repository is from a previous version of Twine. Please submit issues and feature requests in the [current twinejs project](https://github.com/klembot/twinejs/).
