### ISSUE TITLE
suggestion/feature request: edit passages with external editor

### ISSUE THREAD

**Issue by m8ram** [tweecode/twine#198]
It would be useful to be able to edit the contents of a passage in the user's preferred external editor.
That removes the need to implement more features in the internal editor keeping the main application light while leveraging the power of existing tools.

**Comment by mcdemarco** [comment]
I don't think invoking an external editor from a browser is possible in the general case, so you might want to look into a browser plugin (e.g., for Firefox) to do that.

Also, this repository is from a previous version of Twine. Please submit issues and feature requests in the [current twinejs project](https://github.com/klembot/twinejs/).
