### ISSUE TITLE
F12 to exit fullscreen conflicts with "Show Dashboard" in Mac OS X 10.8.3

### ISSUE THREAD

**Issue by chronodm** [tweecode/twine#75]
Steps to reproduce:
1. Double click a Twine passage.
2. From the Passage menu, select "Fullscreen View."

Expected:
- You can exit fullscreen without closing the passage

Actual:
- The only way to exit fullscreen is the F12 key, which is bound to "Show Dashbaord" in OS X Mission Control

Possible fixes:
- Use a different keystroke for enter/exit fullscreen on Mac OS X, such as Opt-Cmd-F
- Allow remapping of the "exit fullscreen" command
- Offer more than one way to exit fullscreen

System information
- Mac OS X 10.8.3
- wxPython2.9-osx-cocoa-py2.7
- Python 2.7.2

**Comment by webbedspace** [comment]
OK, I'll do the Option-Command-F thing.
